(window.webpackJsonp=window.webpackJsonp||[]).push([[102],{410:function(e,t,r){"use strict";r.r(t);var i=r(0),a=Object(i.a)({},(function(){var e=this,t=e._self._c;return t("ContentSlotsDistributor",{attrs:{"slot-key":e.$parent.slotKey}},[t("h1",{attrs:{id:"activity-failures"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#activity-failures"}},[e._v("#")]),e._v(" Activity failures")]),e._v(" "),t("p",[e._v("An activity fails when it encounters an error during its execution. This results in ActivityTaskFailed event in the workflow execution with some details of the error. The different kinds of errors that can be seen in activity failures are listed here.")]),e._v(" "),t("h2",{attrs:{id:"panic-errors"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#panic-errors"}},[e._v("#")]),e._v(" Panic errors")]),e._v(" "),t("p",[e._v("Description: There is a issue in the activity code that is causing a panic.")]),e._v(" "),t("p",[e._v("Mitigation: Panics are usually caused by nil pointer dereferences or out-of-range array access and should never be expected in a workflow. Check the stack trace provided in the error details to find where in the activity code, the panic is seen. Fix the rootcause of the panic.")]),e._v(" "),t("h2",{attrs:{id:"custom-errors"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#custom-errors"}},[e._v("#")]),e._v(" Custom errors")]),e._v(" "),t("p",[e._v("Description: This is a customised error returned by the activity.")]),e._v(" "),t("p",[e._v("Mitigation: This is a way of facilitating error handling done within the activity code. Check your activity code to find where it returns a NewCustomError with some information. This is ideally an expected error scenario and should be handled within the workflow that executed the activity.")]),e._v(" "),t("p",[e._v("Read more about "),t("a",{attrs:{href:"https://cadenceworkflow.io/docs/go-client/error-handling/",target:"_blank",rel:"noopener noreferrer"}},[e._v("error handling"),t("OutboundLink")],1)]),e._v(" "),t("h2",{attrs:{id:"generic-errors"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#generic-errors"}},[e._v("#")]),e._v(" Generic errors")]),e._v(" "),t("p",[e._v("Description: This is an error returned by the activity.")]),e._v(" "),t("p",[e._v("Mitigation: This error is caused by something unexpected within the activity code, typically due to a downstream service that your activity communicates with. Cadence does not know anything about it and just puts all unknown errors in this category. Check your activity code to find the potential error cases. This is ideally an unexpected error scenario and should be debugged further to fix the rootcause.")]),e._v(" "),t("p",[e._v("Read more about "),t("a",{attrs:{href:"https://cadenceworkflow.io/docs/go-client/error-handling/",target:"_blank",rel:"noopener noreferrer"}},[e._v("error handling"),t("OutboundLink")],1)])])}),[],!1,null,null,null);t.default=a.exports}}]);